### ISSUE TITLE
怎么实现一个圆点，在一个园规上移动？

### ISSUE THREAD

**Issue by zh2120** [jiarWang/AnimBezierShape#2]

**Comment by jiarWang** [comment]
在圆规上，还是圆上?你确定要在圆规上么？亲

**Comment by zh2120** [comment]
@jiarWang 是在圆上，圆点是在一个用 ART 写的填充小圆。类似医院里 的给心电图的哪种跳动

**Comment by zh2120** [comment]
@jiarWang 是在圆上，圆点是在一个用 ART 写的填充小圆

**Comment by jiarWang** [comment]
ART图层叠加，Animated动画改变原点坐标动画重绘小圆，这是我目前觉得可以使用的方法，希望对你有帮助
